### ISSUE TITLE
Is this plguin compatible with grafana 6?

### ISSUE THREAD

**Issue by filthz** [pR0Ps/grafana-trackmap-panel#22]
Grafana 6.3.6
I downloaded the latest release (2.0.4) into the plugins folder.
When I try to add the plugin I see the "unable to dynamically transpile es module" error in console.

Am I doing something wrong?

**Comment by pR0Ps** [comment]
I just confirmed that it's working on the newest version of Grafana (v6.4.2).

You may have just gotten the source code instead of the built version. See the instructions [here](https://github.com/pR0Ps/grafana-trackmap-panel#installation) or install the plugin via https://grafana.com/grafana/plugins/pr0ps-trackmap-panel
