### ISSUE TITLE
Support upper case Longitude and Latitude

### ISSUE THREAD

**Issue by MatinF** [pR0Ps/grafana-trackmap-panel#34]
Is it possible to set up the module so that it also supports 'proper' names, i.e. `Longitude` and `Latitude`? Currently we have to do some steps to rename these signals to get them into lower case, which would be ideal to avoid.

Thanks!

**Comment by bigjohnson** [comment]
I like also use it with OwnTracks app that use lat lon labels in json...

**Comment by pR0Ps** [comment]
I'm not sure what you mean. Currently the latitude and longitude is pulled out of the data by grabbing the 1st and 2nd stream provided to the plugin.

See: https://github.com/pR0Ps/grafana-trackmap-panel/blob/34243f391e0787f4bff33eadfd9a8dbab25e7c4e/src/trackmap_ctrl.js#L360-L361

The example query in the readme has "latitude" and "longitude" in it only because that's now my data is stored. If your data is stored differently you'll need to change the query to fit it.

Am I understanding your issue correctly?

**Comment by bigjohnson** [comment]
Many thanks, just tested and works great.
Just one little suggestion, explain it on docs.

**Comment by pR0Ps** [comment]
Fair enough, docs have been changed
